---

git_repo: git@github.com:paolopaolopaolo/do-more-math.git
repo_name: do-more-math

project_name: domoremath
application_name: domoremath

git_ssh_pub_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCtCzLaPOhFezHUU9Xw0/oggByqX5jZSXO5biooIIhlbMgg9N+MwsyQAnXjL5mxsc0cQtWYmhnnG3+NwLobKGHJ06hDHi29STOxXHbizTLnsyxgeTW/kpIaWAqvNbsZvwcRh3BEKuHLrfALnpdLUIYlA22dLXIVeUSs6GbhBKcY88126B+Xb3QFEL4ypnYTTTuJmFkDi8AmNnMutZcDqYKKGrYhhg6RzuzjUqdTY5hC7lrUpR9goqX6rOCD41MY2iWaBhSm1A/k4jcrt3r1lGcxuPu8w4v4weaxqOyKGIhdAZiOtsPZZJ3fcg9T8dYXv9M/5usmgTuUa4sNjUpN+JsbnXIkh3SbzTnw2C8tz/6L1K0WFQjmmnf4EwNq+tA8NSbGeema/emvMOuD36oa6m8qQOVA7LVQ0M1MFI2SDBcssst0s3umqs27E1qn8Kq2vvzh45uMykVf/EGgBOjzS5E2hXYETQbOKPx7Iimy3XAVjeyriAJBdAvHcyhb13ongRDd4uFmiSBRul0xOOGP9jxmNrppkeqeRN+1iT0HOX/kjocvPIMaGPnXDzNsIey8lHV//RCyDfVtl4Ja0Ks0YzGRyrXHFc+o6mmmEkfK1XyQU+8pu7ozViasFF+wrMiMP0Scwy+vMqeRGP0JRpQ90hV43GOPYwaKl4Thcn/LnhVTyQ==
git_ssh_priv_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKAIBAAKCAgEArQsy2jzoRXsx1FPV8NP6IIAcql+Y2UlzuW4qKCCIZWzIIPTf
  jMLMkAJ14y+ZsbHNHELVmJoZ5xt/jcC6GyhhydOoQx4tvUkzsVx24s0y57MsYHk1
  v5KSGlgKrzW7Gb8HEYdwRCrhy63wC56XS1CGJQNtnS1yFXlErOhm4QSnGPPNdugf
  l290BRC+MqZ2E007iZhZA4vAJjZzLrWXA6mCihq2IYYOkc7s41KnU2OYQu5a1KUf
  YKKl+qzgg+NTGNolmgYUptQP5OI3K7d69ZRnMbj7vMOL+MHmsajsihiIXQGYjrbD
  2WSd33IPU/HWF7/TP+brJoE7lGuLDY1KTfibG51yJId0m8058NgvLc/+i9StFhUI
  5pp3+BMDavrQPDUmxnnpmv3przDrg9+qGupvKkDlQOy1UNDNTBSNkgwXLLLLdLN7
  pqrNuxNap/Cqtr784eObjMpFX/xBoATo80uRNoV2BE0Gzij8eyIpst1wFY3sq4gC
  QXQLx3MoW9d6J4EQ3eLhZokgUbpdMTjhj/Y8Zja6aZHqnkTftYk9Bzl/5I6HLzyD
  Ghj51w8zbCHsvJR1f/0Qsg31bZeCWtCrNGMxkcq1xxXPqOppphJHytV8kFPvKbu6
  M1YmrBRfsKzIjD9EnMMvrzKnkRj9CUaUPdIVeNxjj2MGipeE4XJ/y54VU8kCAwEA
  AQKCAgAGNdCtZGIxnCo9pISZEAJ6CB7/Pk8N/UTZ8sowhnpeqXjFNgSP2K3evTfd
  32d0qRzjVsKzp1QmpyX8wF3te5WG2MHBJuQdVvMz+k2J9jNNfXCqRa9YILp9l4tK
  nnMIiYKHboTo7WENHkDvKdHkMg+eZHEaovblLmT4j56hlLkqfBVznwEDPky7oc4x
  oye5qZvpZD5NkkZjGLEpi/rPdtXofuzqZxU+xl5aCi1XIMvmGwfHeeWWYj/yryGf
  mhjxW2LeFDnJgvLPFA9G0l7nUVwivLDMJXhwhQTye02B5z99lwESnhyJQMMpsb47
  FQLJ92htcqwdxaWNvg5PfjKceb+XPwGRDhnuwOpjL7yHkK7elpR3sdC/QYf/txk+
  yzy4+7w5jtg7OT+6NHOfZXrpoPRYCSCh81FrS/qW3W2xawEOoDUMBN7aiIVqkWIi
  T2fqPoDkBuuVIvBWzKU6q1BmcAHSIG+WqHqo7FXbweIiQwhDdgxCJ2ZcQ9iNU23U
  OCijb+ElF/Uz/974jYpmHpZi2W3Jqdko1cxuAPFh4EEacw5iOU6iEniR5GNTXeYX
  eesoaaZbm2BNG09qO3WEVtpFdzf65XWUklLHsqNhPMbXl2WQ0OmbF/SaPBMaH92d
  Cs8IHHiRJH1LLejpnLuMjAIWqOJiwZ4iQ8gpidS+8CXI/0K4wQKCAQEAy2QWg1fF
  xf2KKZM/vrIa12Vvxyko9fE3GhmTf7PKEmQ7Eu6t0Pf2wPdrOcs/HvMfSo5QLAwV
  f7jzdm8Dc1v25KVKzyNJSXpwa8lc4hemWC9rR9tCQ0lokWO9wJm4qZh2HsupKo+b
  zs6E4kfmAUIOdstUcX5oxdRRzu1SRz35Kn+tRNudKGaBEC84DF0jGvdJwczT2uNU
  hU88rgjfhQhbSrYIdeT+eTCpLqWHunlfqJla5LfUzbelQXO4g6thfp79MDnBJgrO
  qrCfxm0qyy5MJru8oVoN2mfIn5PnRsRI2BCPp29ESw0oVUOi/OGpYdyF1Nv7N0ia
  4UWJ66xpvSUYmwKCAQEA2c2c2ty+NULrrOYFAqqPvkDfFvgBUCUYJTeRVUlD77CN
  ri/RJocc/UBNpL+bzzAuEUKUBfRETrKDSEo4UQ9+z32mM0VF8CIxiJRfyYsMOE/M
  1UNVIx96W6AipKDjg3emCHAdTdwNBPqT4hIcaBhsR+wz3B5w0kOFwJ82MMt2jcvc
  CN/p6fsTOKk4oZPxOvuhuIoHBpBz1Id1MfRL0to6D3qUXrYDkwcHblPWeJQymiS3
  MSxnTo1Jw8x6pDmxpGpLvUM0GMPDBQwx0RHgqtU1iht63XTOVbj9QXNOk7kPpdLJ
  gquOQbcyKekmxX4LaEWdQqTC+5YscoQMHBSQWZFRawKCAQATg7blQzammHz5IDet
  hEkvAXyID1ruvgYbavjL9+Qbf6JrXpsuwZvbR+Hx2Z5kyc7myGDI2R/28Tfq1Rvv
  pZM6vOFAnpIZirXeoaNXzg0XyPTyIAdrjU+LI5bBM/6Txx0ON1wzyTOZ1BbL3zoi
  RMQ+gaPIf+htksGGqR6L11ZgzX9CbA/YIH2hn+YwyX7kx3U8MvrgtY8We1PHHvLT
  QMoBkRWeuinwVsrkvt0W9y5GbvBZoYm5czVX4lKBz5+7FmYUinYNwFuz5N5vm2nP
  tNF5pemjUZCis/J73SUDlTGoCW6/Ed3rlYeZJrQsrzohOZddpP2lgEHb+2AQTKqY
  i0ahAoIBAQCs6UR2qLrE0/0ARZiCtl/pvdyegoOgWeKiYUwa9lBd8L96IvIbcTa9
  g5hgi9GpmelowH99fp/gDm6VLH8rM28MUQdqOru8WZkTgh/NhHtOFWRbhtoHSU09
  gpMeObCFxa5lkoRhNKqNYlWXK6OrrIACVW4SeYQ+GWcNNhiygkT7a3WjAgjVPgPT
  fty7whTIK88HD2Vme7XJa0TKRNURbzia40j5K+0Ig5MNrrddAOJvZ2icPFFDln2S
  WTqgOEFkcxLwDXNFmdywnC7MeTHwzdV0cD6Jo9rPSU6d8GnYcxoOHprmB0anu0Wy
  6itirJ9nx6SCrQUy8NUWkOiAPn8e7HRDAoIBAE0Gc0N7MdOYujxXQq9SM+i+Od5M
  MEsqLl+2c9J4pPgP4K16VcsXIB5kTYxr1gKazimayvQrcqih20O608dx0naSgtyM
  O8K4XaY5+ah1VTar3/EY6FErWQQxwjcQJ9TXfJUWu4nXDR/DUyW2LooBV3r95S5Z
  nkL8V9HdV/hlZSiXiVn4jc4IA0jS0vJRDlV+y+LsqgdxqUMWFsvQurKqvWx1gzS4
  02LsnTgaaPW4K0qmMzSudKYBKMpYatXiNFjze6dd+hqyGti1iPH9T/n+Jy10zfiE
  5zFyBEVSj6AWAMe5i4DahLpTqfsqcnHjbNbLSWQP3KyZQgdjFe7fT8KsCEY=
  -----END RSA PRIVATE KEY-----

